version: "3.8"
services:
#  postgres:
#    image: postgres:15
#    container_name: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_DB: postgres
#      POSTGRES_PASSWORD: postgres
#    volumes:
#      - ./db-data:/var/lib/postgresql/data
#    ports:
#      - "6432:5432"
  avito-trainee:
    image: avito-trainee:latest
    container_name: avito-trainee
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        tag: "{{.Name}}"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      PORT: 8080
    expose:
      - 8080
